### ISSUE TITLE
Activating extension brainfit.vscode-coverage-highlighter failed due to an error

### ISSUE THREAD

**Issue by amatosov-rbx** [pilat/vscode-coverage-highlighter#19]
Extension fails to activate on latest VSCode
Version: 1.47.0
Commit: d5e9aa0227e057a60c82568bf31c04730dc15dcd
Date: 2020-07-09T08:01:54.115Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

```
[2020-07-10 21:55:41.403] [exthost] [error] Activating extension brainfit.vscode-coverage-highlighter failed due to an error:
[2020-07-10 21:55:41.403] [exthost] [error] TypeError: Cannot read property 'id' of undefined
	at ProviderManager.onChangeActive (/Users/amatosov/.vscode/extensions/brainfit.vscode-coverage-highlighter-1.0.3/out/src/providerManager.js:49:31)
	at new ProviderManager (/Users/amatosov/.vscode/extensions/brainfit.vscode-coverage-highlighter-1.0.3/out/src/providerManager.js:20:14)
	at /Users/amatosov/.vscode/extensions/brainfit.vscode-coverage-highlighter-1.0.3/out/src/extension.js:32:221
	at Generator.next (<anonymous>)
	at /Users/amatosov/.vscode/extensions/brainfit.vscode-coverage-highlighter-1.0.3/out/src/extension.js:7:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/amatosov/.vscode/extensions/brainfit.vscode-coverage-highlighter-1.0.3/out/src/extension.js:3:12)
	at activate (/Users/amatosov/.vscode/extensions/brainfit.vscode-coverage-highlighter-1.0.3/out/src/extension.js:26:12)
	at Function._callActivateOptional (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:837:509)
	at Function._callActivate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:837:160)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:835:703
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async Promise.all (index 0)
	at async h.$activate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:843:297)
```

**Comment by rfunk** [comment]
This looks like the same problem as #24 , fixed by PR #26
